# Generated by Django 3.2.4 on 2021-08-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('fromdate', models.DateTimeField(verbose_name='start date')),
                ('todate', models.DateTimeField(verbose_name='end date')),
                ('content', models.TextField()),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedate', models.DateTimeField(auto_now=True, null=True)),
                ('deletedate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('github', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedate', models.DateTimeField(auto_now=True, null=True)),
                ('deletedate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('techstack', models.CharField(max_length=200)),
                ('fromdate', models.DateTimeField(verbose_name='start date')),
                ('todate', models.DateTimeField(verbose_name='end date')),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedate', models.DateTimeField(auto_now=True, null=True)),
                ('deletedate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
