# Generated by Django 3.2.6 on 2021-08-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BE_resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('fromdate', models.DateTimeField(null=True, verbose_name='start date')),
                ('todate', models.DateTimeField(null=True, verbose_name='end date')),
                ('content', models.TextField(null=True)),
                ('techstack', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedate', models.DateTimeField(auto_now=True, null=True)),
                ('deletedate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
