# Generated by Django 3.2.6 on 2021-08-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BE_resume', '0003_auto_20210813_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='techstack',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
