# Generated by Django 3.2.6 on 2021-08-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BE_resume', '0004_auto_20210813_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='createdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deletedate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updatedate',
        ),
        migrations.RemoveField(
            model_name='work',
            name='createdate',
        ),
        migrations.RemoveField(
            model_name='work',
            name='deletedate',
        ),
        migrations.RemoveField(
            model_name='work',
            name='updatedate',
        ),
    ]
